# Generated by Django 4.1.1 on 2023-03-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=300)),
                ('asunto', models.CharField(max_length=200, null=True)),
                ('mensaje', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('fecha', models.DateField()),
                ('imagen', models.ImageField(null=True, upload_to='posts')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('sector', models.IntegerField(choices=[[0, 'privado'], [1, 'industrial']])),
            ],
        ),
    ]
